/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SegurancaRouteImport } from './routes/seguranca'
import { Route as RecursosRouteImport } from './routes/recursos'
import { Route as EnergiaRouteImport } from './routes/energia'
import { Route as ComunicacaoRouteImport } from './routes/comunicacao'
import { Route as AmbientalRouteImport } from './routes/ambiental'
import { Route as IndexRouteImport } from './routes/index'

const SegurancaRoute = SegurancaRouteImport.update({
  id: '/seguranca',
  path: '/seguranca',
  getParentRoute: () => rootRouteImport,
} as any)
const RecursosRoute = RecursosRouteImport.update({
  id: '/recursos',
  path: '/recursos',
  getParentRoute: () => rootRouteImport,
} as any)
const EnergiaRoute = EnergiaRouteImport.update({
  id: '/energia',
  path: '/energia',
  getParentRoute: () => rootRouteImport,
} as any)
const ComunicacaoRoute = ComunicacaoRouteImport.update({
  id: '/comunicacao',
  path: '/comunicacao',
  getParentRoute: () => rootRouteImport,
} as any)
const AmbientalRoute = AmbientalRouteImport.update({
  id: '/ambiental',
  path: '/ambiental',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ambiental': typeof AmbientalRoute
  '/comunicacao': typeof ComunicacaoRoute
  '/energia': typeof EnergiaRoute
  '/recursos': typeof RecursosRoute
  '/seguranca': typeof SegurancaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ambiental': typeof AmbientalRoute
  '/comunicacao': typeof ComunicacaoRoute
  '/energia': typeof EnergiaRoute
  '/recursos': typeof RecursosRoute
  '/seguranca': typeof SegurancaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ambiental': typeof AmbientalRoute
  '/comunicacao': typeof ComunicacaoRoute
  '/energia': typeof EnergiaRoute
  '/recursos': typeof RecursosRoute
  '/seguranca': typeof SegurancaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ambiental'
    | '/comunicacao'
    | '/energia'
    | '/recursos'
    | '/seguranca'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ambiental'
    | '/comunicacao'
    | '/energia'
    | '/recursos'
    | '/seguranca'
  id:
    | '__root__'
    | '/'
    | '/ambiental'
    | '/comunicacao'
    | '/energia'
    | '/recursos'
    | '/seguranca'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AmbientalRoute: typeof AmbientalRoute
  ComunicacaoRoute: typeof ComunicacaoRoute
  EnergiaRoute: typeof EnergiaRoute
  RecursosRoute: typeof RecursosRoute
  SegurancaRoute: typeof SegurancaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/seguranca': {
      id: '/seguranca'
      path: '/seguranca'
      fullPath: '/seguranca'
      preLoaderRoute: typeof SegurancaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recursos': {
      id: '/recursos'
      path: '/recursos'
      fullPath: '/recursos'
      preLoaderRoute: typeof RecursosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/energia': {
      id: '/energia'
      path: '/energia'
      fullPath: '/energia'
      preLoaderRoute: typeof EnergiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comunicacao': {
      id: '/comunicacao'
      path: '/comunicacao'
      fullPath: '/comunicacao'
      preLoaderRoute: typeof ComunicacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ambiental': {
      id: '/ambiental'
      path: '/ambiental'
      fullPath: '/ambiental'
      preLoaderRoute: typeof AmbientalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AmbientalRoute: AmbientalRoute,
  ComunicacaoRoute: ComunicacaoRoute,
  EnergiaRoute: EnergiaRoute,
  RecursosRoute: RecursosRoute,
  SegurancaRoute: SegurancaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
